# popclip
name: 
  en: Format JSON
  zh-Hans: 格式化 JSON
  zh-Hant: 格式化 JSON
  ja: JSON 形式
version: 1
identifier: xyz.phpz.popclip.extension.format-json
icon: circle J
javascript: return JSON.stringify(JSON.parse(popclip.input.text), null, 2)
after: paste-result